{% set name = "ubelt" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ubelt-{{ version }}.tar.gz
  sha256: 84e146c1c3ba13a2425eea5d5748bf33ab3f9dbe7ce237eb11e130116ba17441

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python
  run:
    - python

test:
  imports:
    - ubelt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Erotemic/ubelt
  summary: A Python utility belt containing simple tools, a stdlib like feel, and extra batteries.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
