{% set name = "ubelt" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ubelt-{{ version }}.tar.gz
  sha256: 5bf163d4aa830882fc99d776c75df268173490f54baa1f313add7fb3fc06389e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - ubelt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Erotemic/ubelt
  summary: A Python utility belt containing simple tools, a stdlib like feel, and extra batteries.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
