{% set name = "ubelt" %}
{% set version = "1.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ubelt-{{ version }}.tar.gz
  sha256: d42a7006ebe6ea7185219cf73e2e1d7f323549b1d8c1d4b2a2e8751d9cf0b292

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - ubelt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Erotemic/ubelt
  summary: A Python utility belt containing simple tools, a stdlib like feel, and extra batteries.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
