{% set name = "ubelt" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ubelt-{{ version }}.tar.gz
  sha256: 78f1f560fa18a390fd42e9e43696d3c46100958577425f784610ef7bec20b9ea

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - ubelt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Erotemic/ubelt
  summary: A Python utility belt containing simple tools, a stdlib like feel, and extra batteries.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
